### PR TITLE
minimum changes

### PR DESCRIPTION
**Pull request by TRANTUAN-PC**
remove temp files

### CODE REVIEW

**Comment by mast3rz3ro** [comment]
- Why you increased the sleep timeout after iBSS is sent from 3 to 10 ?

**Comment by TRANTUAN-PC** [comment]
> * Why you increased the sleep timeout after iBSS is sent from 3 to 10 ?

In some machines,it needs a little longer to send files.

**Comment by mast3rz3ro** [comment]
- Why have you enabled sending trustcache in 0x8012 ? Do you did this because booting ramdisk fails with 0x8012 ? Which iOS have you tried with this ?

```
-  if [ ! -s "$bootchain"'/trustcache.img4' ] || [ "$cpid" != '0x8012' ]; then
+ if [ ! -s "$bootchain"'/trustcache.img4' ] || [ "$cpid" = '0x8012' ]; then
```

**Comment by TRANTUAN-PC** [comment]
> * Why have you enabled sending trustcache in 0x8012 ? Do you did this because booting ramdisk fails with 0x8012 ? Which iOS have you tried with this ?
> 
> ```
> -  if [ ! -s "$bootchain"'/trustcache.img4' ] || [ "$cpid" != '0x8012' ]; then
> + if [ ! -s "$bootchain"'/trustcache.img4' ] || [ "$cpid" = '0x8012' ]; then
> ```

your code above means if $cpid is different from 0x8012,then do nothing(trustcache can not be sent with other $cpid)

**Comment by mast3rz3ro** [comment]
Alright, that was quite confusing but it's appears that i have used the wrong operator, the above if statements fails because the `||` operator continues comparing even if one of condiation are true so insted we must used `&&` operator which stops when one of condiations are not true. For more reference check [here](https://unix.stackexchange.com/questions/24684/confusing-use-of-and-operators)

**Comment by mast3rz3ro** [comment]
Please send another pull request with minimum change and style following

I'll close this pull now but I'll be waiting for your updated pull request.

**Pull request closed without merging**
